# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{arkayne_rails}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marc Chung"]
  s.date = %q{2010-08-29}
  s.description = %q{Get recommendations from Arkayne. Sign up at http://arkayne.com/login}
  s.email = %q{mchung@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "arkayne_rails.gemspec",
     "generators/arkayne_rails/README",
     "generators/arkayne_rails/USAGE",
     "generators/arkayne_rails/arkayne_rails_generator.rb",
     "generators/arkayne_rails/install.rb",
     "generators/arkayne_rails/templates/config/arkayne.yml",
     "generators/arkayne_rails/templates/config/initializers/arkayne_init.rb",
     "generators/arkayne_rails/templates/lib/arkayne_api_helper.rb",
     "generators/arkayne_rails/templates/lib/tasks/arkayne.rake",
     "lib/arkayne_rails.rb",
     "test/helper.rb",
     "test/test_arkayne_rails.rb"
  ]
  s.homepage = %q{http://github.com/mchung/arkayne_rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Arkayne Ruby on Rails plugin}
  s.test_files = [
    "test/helper.rb",
     "test/test_arkayne_rails.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

